"""update blog table

Revision ID: 51bb5b79af2c
Revises: 891ae5f3914c
Create Date: 2021-05-04 18:25:00.591334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb5b79af2c'
down_revision = '891ae5f3914c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'subtitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('subtitle', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
